os: linux
dist: bionic
language: python
python:
  - 3.6
  - 3.7
  - 3.8
  - 3.9

before_install:
  - sudo apt-get -yq install software-properties-common
  - sudo apt-add-repository -y multiverse
  - sudo apt-get -yq update
  - sudo apt-get -yq install automake build-essential libyaml-dev libmagic-dev cython autoconf libffi-dev libfuzzy-dev unzip libimage-exiftool-perl swig
  - pip install stoq-framework
  - wget -O /tmp/xorsearch.zip https://github.com/DidierStevens/FalsePositives/raw/master/XORSearch_V1_11_3.zip
  - unzip /tmp/xorsearch.zip -d /tmp
  - sudo gcc -o /usr/local/bin/xorsearch /tmp/XORSearch.c
  - sed -i "s@bin_path = xorsearch@bin_path = /usr/local/bin/xorsearch@" $(find . -name 'xorsearch.stoq')

install:
  - pip install -r hash_ssdeep/requirements.txt
  - pip install -r javaclass/requirements.txt
  - pip install -r mimetype/requirements.txt
  - pip install -r xordecode/requirements.txt
  - pip install -r yara/requirements.txt

script:
  - python b64decode/setup.py test
  - python entropy/setup.py test
  - python exif/setup.py test
  - python hash/setup.py test
  - python hash_ssdeep/setup.py test
  - python javaclass/setup.py test
  - python mimetype/setup.py test
  - python xordecode/setup.py test
  - python xorsearch/setup.py test
  - python yara/setup.py test
